// Generated by scripts/generate_http_contracts.py from contracts/http/v1/openapi.json (sha256: 0b0bc8390c29b5767d8d8d8f2bf66e8dd28c4377068836c06b9bc85606b2d395).
// Do not edit directly.

export type DeckButtonKind = "session" | "control" | "empty";

export type DeckIconName = "cursor" | "claude" | "plus" | "arrow-left" | "arrow-right" | "arrows-clockwise" | "robot" | "terminal" | "code" | "bug" | "wrench" | "rocket" | "shield" | "database" | "globe" | "package" | "git-branch" | "flask" | "check" | "git-pull-request" | "git-commit" | "article" | "fire" | "fire-extinguisher" | "fire-truck" | "magnifying-glass" | "bell" | "test-tube" | "checks" | "eye" | "shield-check";

export type DeckButtonColor = "idle" | "working" | "waiting" | "done" | "error" | "unknown" | "control";

export type DeckButtonConfidence = "observed" | "candidate" | "persisted" | "unknown";

export type DeckButtonAction = "choose_new_provider" | "cancel_new_session" | "new_session" | "refresh_sessions" | "previous_page" | "next_page" | "choose_session_icon" | "set_session_icon" | "choose_slot_command" | "set_slot_command" | "cancel_picker" | "previous_picker_page" | "next_picker_page" | "execute_command";

export type DeckAction = DeckButtonAction | "focus_session";

export type CommandID = "accept" | "commit_push" | "create_pr" | "compact";

export interface DeckButton {
  id: string;
  position: number;
  kind: DeckButtonKind;
  label: string;
  detail: string;
  icon: DeckIconName;
  color: DeckButtonColor;
  selected: boolean;
  enabled: boolean;
  confidence: DeckButtonConfidence;
  provider_id: string | null;
  session_id?: string | null;
  action?: DeckButtonAction | null;
  command_id?: CommandID | null;
  option_id?: string | null;
}

export interface DeckSnapshot {
  revision: number;
  observed_at_ms: number;
  source: string;
  read_only: boolean;
  selected_session_id: string | null;
  page: number;
  page_count: number;
  has_previous: boolean;
  has_next: boolean;
  buttons: Array<DeckButton>;
}

export interface DeckActionRequest {
  client_id: string;
  button_id: string;
  revision: number;
}

export interface DeckActionResponse {
  accepted: boolean;
  action: DeckAction;
  snapshot?: DeckSnapshot;
  focus?: Record<string, unknown>;
  launch?: Record<string, unknown>;
  command?: Record<string, unknown>;
}

export interface HealthResponse {
  status: "ok";
  focus_enabled: boolean;
  launch_enabled: boolean;
  actions_enabled: boolean;
  providers: Record<string, Array<string>>;
  unavailable_providers: Record<string, string>;
  accessibility_trusted: boolean;
}

export interface APIErrorResponse {
  error: string;
  retryable?: boolean | null;
}

export type DeckActivationResponse = DeckActionResponse;

interface Schema {
  $ref?: string;
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  oneOf?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  items?: Schema;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
  "x-uniqueProperty"?: string;
}

const SCHEMAS: Record<string, Schema> = {
  "APIErrorResponse": {
    "additionalProperties": false,
    "properties": {
      "error": {
        "minLength": 1,
        "type": "string"
      },
      "retryable": {
        "type": [
          "boolean",
          "null"
        ]
      }
    },
    "required": [
      "error"
    ],
    "type": "object"
  },
  "CommandID": {
    "enum": [
      "accept",
      "commit_push",
      "create_pr",
      "compact"
    ],
    "type": "string"
  },
  "DeckAction": {
    "enum": [
      "choose_new_provider",
      "cancel_new_session",
      "new_session",
      "refresh_sessions",
      "previous_page",
      "next_page",
      "choose_session_icon",
      "set_session_icon",
      "choose_slot_command",
      "set_slot_command",
      "cancel_picker",
      "previous_picker_page",
      "next_picker_page",
      "execute_command"
    ],
    "type": "string"
  },
  "DeckActionRequest": {
    "additionalProperties": false,
    "properties": {
      "button_id": {
        "minLength": 1,
        "type": "string"
      },
      "client_id": {
        "maxLength": 64,
        "minLength": 1,
        "pattern": "^[A-Za-z0-9._-]+$",
        "type": "string"
      },
      "revision": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "client_id",
      "button_id",
      "revision"
    ],
    "type": "object"
  },
  "DeckActionResponse": {
    "additionalProperties": false,
    "properties": {
      "accepted": {
        "type": "boolean"
      },
      "action": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/DeckAction"
          },
          {
            "const": "focus_session"
          }
        ]
      },
      "command": {
        "additionalProperties": true,
        "type": "object"
      },
      "focus": {
        "additionalProperties": true,
        "type": "object"
      },
      "launch": {
        "additionalProperties": true,
        "type": "object"
      },
      "snapshot": {
        "$ref": "#/components/schemas/DeckSnapshot"
      }
    },
    "required": [
      "accepted",
      "action"
    ],
    "type": "object"
  },
  "DeckButton": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/DeckAction"
          },
          {
            "type": "null"
          }
        ]
      },
      "color": {
        "$ref": "#/components/schemas/DeckButtonColor"
      },
      "command_id": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/CommandID"
          },
          {
            "type": "null"
          }
        ]
      },
      "confidence": {
        "$ref": "#/components/schemas/DeckButtonConfidence"
      },
      "detail": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "icon": {
        "$ref": "#/components/schemas/DeckIconName"
      },
      "id": {
        "minLength": 1,
        "type": "string"
      },
      "kind": {
        "$ref": "#/components/schemas/DeckButtonKind"
      },
      "label": {
        "type": "string"
      },
      "option_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "position": {
        "maximum": 14,
        "minimum": 0,
        "type": "integer"
      },
      "provider_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "selected": {
        "type": "boolean"
      },
      "session_id": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "required": [
      "id",
      "position",
      "kind",
      "label",
      "detail",
      "icon",
      "color",
      "selected",
      "enabled",
      "confidence",
      "provider_id"
    ],
    "type": "object"
  },
  "DeckButtonColor": {
    "enum": [
      "idle",
      "working",
      "waiting",
      "done",
      "error",
      "unknown",
      "control"
    ],
    "type": "string"
  },
  "DeckButtonConfidence": {
    "enum": [
      "observed",
      "candidate",
      "persisted",
      "unknown"
    ],
    "type": "string"
  },
  "DeckButtonKind": {
    "enum": [
      "session",
      "control",
      "empty"
    ],
    "type": "string"
  },
  "DeckIconName": {
    "enum": [
      "cursor",
      "claude",
      "plus",
      "arrow-left",
      "arrow-right",
      "arrows-clockwise",
      "robot",
      "terminal",
      "code",
      "bug",
      "wrench",
      "rocket",
      "shield",
      "database",
      "globe",
      "package",
      "git-branch",
      "flask",
      "check",
      "git-pull-request",
      "git-commit",
      "article",
      "fire",
      "fire-extinguisher",
      "fire-truck",
      "magnifying-glass",
      "bell",
      "test-tube",
      "checks",
      "eye",
      "shield-check"
    ],
    "type": "string"
  },
  "DeckSnapshot": {
    "additionalProperties": false,
    "properties": {
      "buttons": {
        "items": {
          "$ref": "#/components/schemas/DeckButton"
        },
        "maxItems": 15,
        "minItems": 15,
        "type": "array",
        "x-uniqueProperty": "position"
      },
      "has_next": {
        "type": "boolean"
      },
      "has_previous": {
        "type": "boolean"
      },
      "observed_at_ms": {
        "minimum": 0,
        "type": "integer"
      },
      "page": {
        "minimum": 0,
        "type": "integer"
      },
      "page_count": {
        "minimum": 1,
        "type": "integer"
      },
      "read_only": {
        "type": "boolean"
      },
      "revision": {
        "minimum": 0,
        "type": "integer"
      },
      "selected_session_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "source": {
        "type": "string"
      }
    },
    "required": [
      "revision",
      "observed_at_ms",
      "source",
      "read_only",
      "selected_session_id",
      "page",
      "page_count",
      "has_previous",
      "has_next",
      "buttons"
    ],
    "type": "object"
  },
  "HealthResponse": {
    "additionalProperties": false,
    "properties": {
      "accessibility_trusted": {
        "type": "boolean"
      },
      "actions_enabled": {
        "type": "boolean"
      },
      "focus_enabled": {
        "type": "boolean"
      },
      "launch_enabled": {
        "type": "boolean"
      },
      "providers": {
        "additionalProperties": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "type": "object"
      },
      "status": {
        "const": "ok",
        "type": "string"
      },
      "unavailable_providers": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      }
    },
    "required": [
      "status",
      "focus_enabled",
      "launch_enabled",
      "actions_enabled",
      "providers",
      "unavailable_providers",
      "accessibility_trusted"
    ],
    "type": "object"
  }
};

export function parseDeckSnapshot(value: unknown): DeckSnapshot {
  const buttons = isRecord(value) ? value.buttons : undefined
  const snapshotSchema = contractSchema("DeckSnapshot")
  const buttonSchema = snapshotSchema.properties?.buttons
  const expectedCount = buttonSchema?.minItems
  if (
    !Array.isArray(buttons) ||
    buttonSchema === undefined ||
    expectedCount === undefined ||
    buttonSchema.maxItems !== expectedCount ||
    buttons.length !== expectedCount
  ) {
    throw new Error(`snapshot must contain exactly ${expectedCount ?? "the required number of"} buttons`)
  }
  const positions = buttons.map((button) => isRecord(button) ? button.position : undefined)
  if (
    new Set(positions).size !== buttons.length ||
    positions.some((position) =>
      typeof position !== "number" ||
      !Number.isSafeInteger(position) ||
      position < 0 ||
      position >= expectedCount
    )
  ) {
    throw new Error(`snapshot buttons must occupy each position from 0 through ${expectedCount - 1} exactly once`)
  }
  validate(value, snapshotSchema, "snapshot")
  return value as DeckSnapshot
}

export function parseActivationResponse(value: unknown): DeckActionResponse {
  validate(value, contractSchema("DeckActionResponse"), "activation response")
  return value as DeckActionResponse
}

export function parseHealthResponse(value: unknown): HealthResponse {
  validate(value, contractSchema("HealthResponse"), "health response")
  return value as HealthResponse
}

export function parseAPIErrorResponse(value: unknown): APIErrorResponse {
  validate(value, contractSchema("APIErrorResponse"), "error response")
  return value as APIErrorResponse
}

export function parseDeckActionRequest(value: unknown): DeckActionRequest {
  validate(value, contractSchema("DeckActionRequest"), "action request")
  return value as DeckActionRequest
}

function validate(value: unknown, schema: Schema, path: string): void {
  if (schema.$ref !== undefined) {
    const name = schema.$ref.split("/").at(-1)
    const referenced = name === undefined ? undefined : SCHEMAS[name]
    if (referenced === undefined) {
      throw new Error(`${path} references an unknown schema`)
    }
    validate(value, referenced, path)
    return
  }
  if (schema.oneOf !== undefined) {
    const matches = schema.oneOf.filter((choice) => {
      try {
        validate(value, choice, path)
        return true
      } catch {
        return false
      }
    })
    if (matches.length !== 1) throw new Error(`${path} does not match exactly one allowed shape`)
    return
  }
  if (schema.const !== undefined && value !== schema.const) {
    throw new Error(`${path} must equal ${String(schema.const)}`)
  }
  if (schema.enum !== undefined && !schema.enum.includes(value)) {
    throw new Error(`${path} is unsupported`)
  }

  const allowedTypes = Array.isArray(schema.type) ? schema.type : [schema.type]
  if (allowedTypes.includes("null") && value === null) return
  const kind = allowedTypes.find((candidate) => candidate !== "null")
  if (kind === undefined) {
    if (allowedTypes.includes("null")) throw new Error(`${path} must be null`)
    return
  }

  if (kind === "object") {
    if (!isRecord(value)) throw new Error(`${path} must be an object`)
    const properties = schema.properties ?? {}
    for (const required of schema.required ?? []) {
      if (!Object.prototype.hasOwnProperty.call(value, required)) {
        throw new Error(`${path}.${required} is required`)
      }
    }
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(value)) {
        if (properties[key] === undefined) throw new Error(`${path}.${key} is not allowed`)
      }
    }
    for (const [key, propertySchema] of Object.entries(properties)) {
      if (Object.prototype.hasOwnProperty.call(value, key)) {
        validate(value[key], propertySchema, `${path}.${key}`)
      }
    }
    if (typeof schema.additionalProperties === "object") {
      for (const [key, item] of Object.entries(value)) {
        if (properties[key] === undefined) validate(item, schema.additionalProperties, `${path}.${key}`)
      }
    }
    return
  }
  if (kind === "array") {
    if (!Array.isArray(value)) throw new Error(`${path} must be an array`)
    if (schema.minItems !== undefined && value.length < schema.minItems) {
      throw new Error(`${path} must contain at least ${schema.minItems} items`)
    }
    if (schema.maxItems !== undefined && value.length > schema.maxItems) {
      throw new Error(`${path} must contain at most ${schema.maxItems} items`)
    }
    value.forEach((item, index) => validate(item, schema.items ?? {}, `${path}[${index}]`))
    if (schema.uniqueItems && new Set(value.map(stableValue)).size !== value.length) {
      throw new Error(`${path} items must be unique`)
    }
    const uniqueProperty = schema["x-uniqueProperty"]
    if (uniqueProperty !== undefined) {
      const values = value.map((item) => isRecord(item) ? item[uniqueProperty] : undefined)
      if (new Set(values.map(stableValue)).size !== value.length) {
        throw new Error(`${path}.${uniqueProperty} values must be unique`)
      }
    }
    return
  }
  if (kind === "string") {
    if (typeof value !== "string") throw new Error(`${path} must be a string`)
    if (schema.minLength !== undefined && value.length < schema.minLength) {
      throw new Error(`${path} is too short`)
    }
    if (schema.maxLength !== undefined && value.length > schema.maxLength) {
      throw new Error(`${path} is too long`)
    }
    if (schema.pattern !== undefined && !new RegExp(schema.pattern).test(value)) {
      throw new Error(`${path} has an invalid format`)
    }
    return
  }
  if (kind === "integer") {
    if (typeof value !== "number" || !Number.isSafeInteger(value)) {
      throw new Error(`${path} must be an integer`)
    }
    validateBounds(value, schema, path)
    return
  }
  if (kind === "number") {
    if (typeof value !== "number" || !Number.isFinite(value)) {
      throw new Error(`${path} must be a number`)
    }
    validateBounds(value, schema, path)
    return
  }
  if (kind === "boolean" && typeof value !== "boolean") {
    throw new Error(`${path} must be a boolean`)
  }
}

function validateBounds(value: number, schema: Schema, path: string): void {
  if (schema.minimum !== undefined && value < schema.minimum) {
    throw new Error(`${path} must be at least ${schema.minimum}`)
  }
  if (schema.maximum !== undefined && value > schema.maximum) {
    throw new Error(`${path} must be at most ${schema.maximum}`)
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function stableValue(value: unknown): string {
  return JSON.stringify(value)
}

function contractSchema(name: string): Schema {
  const schema = SCHEMAS[name]
  if (schema === undefined) throw new Error(`generated schema ${name} is unavailable`)
  return schema
}
