// Generated by scripts/generate_http_contracts.py from contracts/http/v1/openapi.json (sha256: 2581b55d3185b4ab7c96288d3355aef1e765edaddab2db560f66614895e91077).
// Do not edit directly.

import Foundation

public enum DeckButtonKind: String, Codable, Sendable {
    case session
    case control
    case empty
}

public enum DeckIcon: String, Codable, Sendable {
    case cursor
    case claude
    case plus
    case arrowLeft = "arrow-left"
    case arrowRight = "arrow-right"
    case arrowsClockwise = "arrows-clockwise"
    case robot
    case terminal
    case code
    case bug
    case wrench
    case rocket
    case shield
    case database
    case globe
    case package
    case gitBranch = "git-branch"
    case flask
    case check
    case gitPullRequest = "git-pull-request"
    case gitCommit = "git-commit"
    case article
    case fire
    case fireExtinguisher = "fire-extinguisher"
    case fireTruck = "fire-truck"
    case magnifyingGlass = "magnifying-glass"
    case bell
    case testTube = "test-tube"
    case checks
    case eye
    case shieldCheck = "shield-check"
}

public enum DeckColor: String, Codable, Sendable {
    case idle
    case working
    case waiting
    case done
    case error
    case unknown
    case control
}

public enum DeckConfidence: String, Codable, Sendable {
    case observed
    case candidate
    case persisted
    case unknown
}

public enum DeckAction: String, Codable, Sendable {
    case chooseNewProvider = "choose_new_provider"
    case cancelNewSession = "cancel_new_session"
    case newSession = "new_session"
    case refreshSessions = "refresh_sessions"
    case previousPage = "previous_page"
    case nextPage = "next_page"
    case chooseSessionIcon = "choose_session_icon"
    case setSessionIcon = "set_session_icon"
    case chooseSlotCommand = "choose_slot_command"
    case setSlotCommand = "set_slot_command"
    case cancelPicker = "cancel_picker"
    case previousPickerPage = "previous_picker_page"
    case nextPickerPage = "next_picker_page"
    case executeCommand = "execute_command"
}

public enum CommandID: String, Codable, Hashable, Sendable {
    case accept
    case commitPush = "commit_push"
    case createPR = "create_pr"
    case compact
}

public enum DeckResponseAction: String, Codable, Sendable {
    case chooseNewProvider = "choose_new_provider"
    case cancelNewSession = "cancel_new_session"
    case newSession = "new_session"
    case refreshSessions = "refresh_sessions"
    case previousPage = "previous_page"
    case nextPage = "next_page"
    case chooseSessionIcon = "choose_session_icon"
    case setSessionIcon = "set_session_icon"
    case chooseSlotCommand = "choose_slot_command"
    case setSlotCommand = "set_slot_command"
    case cancelPicker = "cancel_picker"
    case previousPickerPage = "previous_picker_page"
    case nextPickerPage = "next_picker_page"
    case executeCommand = "execute_command"
    case focusSession = "focus_session"
}

public struct DeckButton: Codable, Equatable, Sendable {
    public let id: String
    public let position: Int
    public let kind: DeckButtonKind
    public let label: String
    public let detail: String
    public let icon: DeckIcon
    public let color: DeckColor
    public let selected: Bool
    public let enabled: Bool
    public let confidence: DeckConfidence
    public let sessionID: String?
    public let action: DeckAction?
    public let providerID: String?
    public let commandID: CommandID?
    public let optionID: String?

    public init(
        id: String,
        position: Int,
        kind: DeckButtonKind,
        label: String,
        detail: String,
        icon: DeckIcon,
        color: DeckColor = .control,
        selected: Bool = false,
        enabled: Bool,
        confidence: DeckConfidence = .observed,
        sessionID: String? = nil,
        action: DeckAction? = nil,
        providerID: String? = nil,
        commandID: CommandID? = nil,
        optionID: String? = nil
    ) {
        self.id = id
        self.position = position
        self.kind = kind
        self.label = label
        self.detail = detail
        self.icon = icon
        self.color = color
        self.selected = selected
        self.enabled = enabled
        self.confidence = confidence
        self.sessionID = sessionID
        self.action = action
        self.providerID = providerID
        self.commandID = commandID
        self.optionID = optionID
    }

    private enum CodingKeys: String, CodingKey {
        case id, position, kind, label, detail, icon, color, selected, enabled
        case confidence, action
        case sessionID = "session_id"
        case providerID = "provider_id"
        case commandID = "command_id"
        case optionID = "option_id"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(position, forKey: .position)
        try container.encode(kind, forKey: .kind)
        try container.encode(label, forKey: .label)
        try container.encode(detail, forKey: .detail)
        try container.encode(icon, forKey: .icon)
        try container.encode(color, forKey: .color)
        try container.encode(selected, forKey: .selected)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(confidence, forKey: .confidence)
        try container.encode(sessionID, forKey: .sessionID)
        try container.encode(action, forKey: .action)
        try container.encode(providerID, forKey: .providerID)
        try container.encode(commandID, forKey: .commandID)
        try container.encode(optionID, forKey: .optionID)
    }
}

public struct DeckSnapshot: Codable, Equatable, Sendable {
    public let revision: Int
    public let observedAtMilliseconds: Int64
    public let source: String
    public let readOnly: Bool
    public let selectedSessionID: String?
    public let page: Int
    public let pageCount: Int
    public let hasPrevious: Bool
    public let hasNext: Bool
    public let buttons: [DeckButton]

    public init(
        revision: Int,
        observedAtMilliseconds: Int64,
        source: String,
        readOnly: Bool,
        selectedSessionID: String?,
        page: Int,
        pageCount: Int,
        hasPrevious: Bool,
        hasNext: Bool,
        buttons: [DeckButton]
    ) {
        self.revision = revision
        self.observedAtMilliseconds = observedAtMilliseconds
        self.source = source
        self.readOnly = readOnly
        self.selectedSessionID = selectedSessionID
        self.page = page
        self.pageCount = pageCount
        self.hasPrevious = hasPrevious
        self.hasNext = hasNext
        self.buttons = buttons
    }

    private enum CodingKeys: String, CodingKey {
        case revision, source, page, buttons
        case observedAtMilliseconds = "observed_at_ms"
        case readOnly = "read_only"
        case selectedSessionID = "selected_session_id"
        case pageCount = "page_count"
        case hasPrevious = "has_previous"
        case hasNext = "has_next"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
        try container.encode(observedAtMilliseconds, forKey: .observedAtMilliseconds)
        try container.encode(source, forKey: .source)
        try container.encode(readOnly, forKey: .readOnly)
        try container.encode(selectedSessionID, forKey: .selectedSessionID)
        try container.encode(page, forKey: .page)
        try container.encode(pageCount, forKey: .pageCount)
        try container.encode(hasPrevious, forKey: .hasPrevious)
        try container.encode(hasNext, forKey: .hasNext)
        try container.encode(buttons, forKey: .buttons)
    }
}

public struct HealthResponse: Codable, Equatable, Sendable {
    public let status: String
    public let focusEnabled: Bool
    public let launchEnabled: Bool
    public let actionsEnabled: Bool
    public let providers: [String: [String]]
    public let unavailableProviders: [String: String]
    public let accessibilityTrusted: Bool

    public init(
        status: String = "ok",
        focusEnabled: Bool,
        launchEnabled: Bool,
        actionsEnabled: Bool,
        providers: [String: [String]],
        unavailableProviders: [String: String],
        accessibilityTrusted: Bool
    ) {
        self.status = status
        self.focusEnabled = focusEnabled
        self.launchEnabled = launchEnabled
        self.actionsEnabled = actionsEnabled
        self.providers = providers
        self.unavailableProviders = unavailableProviders
        self.accessibilityTrusted = accessibilityTrusted
    }

    private enum CodingKeys: String, CodingKey {
        case status, providers
        case focusEnabled = "focus_enabled"
        case launchEnabled = "launch_enabled"
        case actionsEnabled = "actions_enabled"
        case unavailableProviders = "unavailable_providers"
        case accessibilityTrusted = "accessibility_trusted"
    }
}

public struct APIErrorResponse: Codable, Equatable, Sendable {
    public let error: String
    public let retryable: Bool?

    public init(error: String, retryable: Bool? = nil) {
        self.error = error
        self.retryable = retryable
    }
}

public struct DeckActionRequest: Codable, Equatable, Sendable {
    public let clientID: String
    public let buttonID: String
    public let revision: Int

    public init(clientID: String, buttonID: String, revision: Int) {
        self.clientID = clientID
        self.buttonID = buttonID
        self.revision = revision
    }

    private enum CodingKeys: String, CodingKey {
        case clientID = "client_id"
        case buttonID = "button_id"
        case revision
    }
}

public struct DeckActivationResponse: Codable, Equatable, Sendable {
    public let accepted: Bool
    public let action: DeckResponseAction
    public let snapshot: DeckSnapshot?
    public let focus: [String: JSONValue]?
    public let launch: [String: JSONValue]?
    public let command: [String: JSONValue]?

    public init(
        accepted: Bool,
        action: DeckResponseAction,
        snapshot: DeckSnapshot? = nil,
        focus: [String: JSONValue]? = nil,
        launch: [String: JSONValue]? = nil,
        command: [String: JSONValue]? = nil
    ) {
        self.accepted = accepted
        self.action = action
        self.snapshot = snapshot
        self.focus = focus
        self.launch = launch
        self.command = command
    }

    public init(
        accepted: Bool,
        action: DeckAction,
        snapshot: DeckSnapshot? = nil
    ) {
        self.init(
            accepted: accepted,
            action: DeckResponseAction(rawValue: action.rawValue)!,
            snapshot: snapshot
        )
    }
}
