#!/usr/bin/env python3
"""Generate and check elChango HTTP contracts from OpenAPI 3.1.

The versioned OpenAPI document is the only input. Generated files are written
deterministically and contain both static models and runtime response
validators. Use --check in CI to fail when generated files drift.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/http/v1/openapi.json"
SWIFT_OUTPUT = (
    ROOT / "macos-app/Sources/ElChangoCore/Contracts/HTTPContracts.swift"
)
WEB_OUTPUT = ROOT / "web/src/lib/contracts.ts"
STREAMDECK_OUTPUT = ROOT / "plugins/streamdeck/src/contracts.ts"
OUTPUTS = (SWIFT_OUTPUT, WEB_OUTPUT, STREAMDECK_OUTPUT)


def generated_header(document: dict[str, Any]) -> str:
    canonical = json.dumps(
        document,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode()
    digest = hashlib.sha256(canonical).hexdigest()
    return (
        "Generated by scripts/generate_http_contracts.py from "
        f"contracts/http/v1/openapi.json (sha256: {digest})."
    )


def load_source() -> dict[str, Any]:
    document = json.loads(SOURCE.read_text())
    if document.get("openapi") != "3.1.0":
        raise ValueError("contract source must use OpenAPI 3.1.0")
    paths = document.get("paths", {})
    forbidden = {"/api/focus", "/api/intent"} & paths.keys()
    if forbidden:
        raise ValueError(f"removed paths are present: {sorted(forbidden)}")
    return document


def schemas(document: dict[str, Any]) -> dict[str, Any]:
    return document["components"]["schemas"]


def enum_values(all_schemas: dict[str, Any], name: str) -> list[str]:
    values = all_schemas[name].get("enum")
    if not isinstance(values, list) or not all(isinstance(value, str) for value in values):
        raise ValueError(f"{name} must be a string enum")
    return values


def swift_case(value: str) -> str:
    if value == "create_pr":
        return "createPR"
    pieces = re.split(r"[-_]", value)
    candidate = pieces[0] + "".join(piece.capitalize() for piece in pieces[1:])
    if candidate == "default":
        return "`default`"
    return candidate


def swift_enum(name: str, values: list[str]) -> str:
    cases = []
    for value in values:
        case = swift_case(value)
        suffix = "" if case == value else f' = "{value}"'
        cases.append(f"    case {case}{suffix}")
    return (
        f"public enum {name}: String, Codable, Sendable {{\n"
        + "\n".join(cases)
        + "\n}"
    )


def render_swift(document: dict[str, Any]) -> str:
    all_schemas = schemas(document)
    header = generated_header(document)
    response_action = enum_values(all_schemas, "DeckAction") + ["focus_session"]
    enums = "\n\n".join(
        [
            swift_enum("DeckButtonKind", enum_values(all_schemas, "DeckButtonKind")),
            swift_enum("DeckIcon", enum_values(all_schemas, "DeckIconName")),
            swift_enum("DeckColor", enum_values(all_schemas, "DeckButtonColor")),
            swift_enum(
                "DeckConfidence",
                enum_values(all_schemas, "DeckButtonConfidence"),
            ),
            swift_enum("DeckAction", enum_values(all_schemas, "DeckAction")),
            swift_enum("CommandID", enum_values(all_schemas, "CommandID")).replace(
                "Codable, Sendable", "Codable, Hashable, Sendable"
            ),
            swift_enum("DeckResponseAction", response_action),
        ]
    )
    return f"""// {header}
// Do not edit directly.

import Foundation

{enums}

public struct DeckButton: Codable, Equatable, Sendable {{
    public let id: String
    public let position: Int
    public let kind: DeckButtonKind
    public let label: String
    public let detail: String
    public let icon: DeckIcon
    public let color: DeckColor
    public let selected: Bool
    public let enabled: Bool
    public let confidence: DeckConfidence
    public let sessionID: String?
    public let action: DeckAction?
    public let providerID: String?
    public let commandID: CommandID?
    public let optionID: String?

    public init(
        id: String,
        position: Int,
        kind: DeckButtonKind,
        label: String,
        detail: String,
        icon: DeckIcon,
        color: DeckColor = .control,
        selected: Bool = false,
        enabled: Bool,
        confidence: DeckConfidence = .observed,
        sessionID: String? = nil,
        action: DeckAction? = nil,
        providerID: String? = nil,
        commandID: CommandID? = nil,
        optionID: String? = nil
    ) {{
        self.id = id
        self.position = position
        self.kind = kind
        self.label = label
        self.detail = detail
        self.icon = icon
        self.color = color
        self.selected = selected
        self.enabled = enabled
        self.confidence = confidence
        self.sessionID = sessionID
        self.action = action
        self.providerID = providerID
        self.commandID = commandID
        self.optionID = optionID
    }}

    private enum CodingKeys: String, CodingKey {{
        case id, position, kind, label, detail, icon, color, selected, enabled
        case confidence, action
        case sessionID = "session_id"
        case providerID = "provider_id"
        case commandID = "command_id"
        case optionID = "option_id"
    }}

    public func encode(to encoder: Encoder) throws {{
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(position, forKey: .position)
        try container.encode(kind, forKey: .kind)
        try container.encode(label, forKey: .label)
        try container.encode(detail, forKey: .detail)
        try container.encode(icon, forKey: .icon)
        try container.encode(color, forKey: .color)
        try container.encode(selected, forKey: .selected)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(confidence, forKey: .confidence)
        try container.encode(sessionID, forKey: .sessionID)
        try container.encode(action, forKey: .action)
        try container.encode(providerID, forKey: .providerID)
        try container.encode(commandID, forKey: .commandID)
        try container.encode(optionID, forKey: .optionID)
    }}
}}

public struct DeckSnapshot: Codable, Equatable, Sendable {{
    public let revision: Int
    public let observedAtMilliseconds: Int64
    public let source: String
    public let readOnly: Bool
    public let selectedSessionID: String?
    public let page: Int
    public let pageCount: Int
    public let hasPrevious: Bool
    public let hasNext: Bool
    public let buttons: [DeckButton]

    public init(
        revision: Int,
        observedAtMilliseconds: Int64,
        source: String,
        readOnly: Bool,
        selectedSessionID: String?,
        page: Int,
        pageCount: Int,
        hasPrevious: Bool,
        hasNext: Bool,
        buttons: [DeckButton]
    ) {{
        self.revision = revision
        self.observedAtMilliseconds = observedAtMilliseconds
        self.source = source
        self.readOnly = readOnly
        self.selectedSessionID = selectedSessionID
        self.page = page
        self.pageCount = pageCount
        self.hasPrevious = hasPrevious
        self.hasNext = hasNext
        self.buttons = buttons
    }}

    private enum CodingKeys: String, CodingKey {{
        case revision, source, page, buttons
        case observedAtMilliseconds = "observed_at_ms"
        case readOnly = "read_only"
        case selectedSessionID = "selected_session_id"
        case pageCount = "page_count"
        case hasPrevious = "has_previous"
        case hasNext = "has_next"
    }}

    public func encode(to encoder: Encoder) throws {{
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
        try container.encode(observedAtMilliseconds, forKey: .observedAtMilliseconds)
        try container.encode(source, forKey: .source)
        try container.encode(readOnly, forKey: .readOnly)
        try container.encode(selectedSessionID, forKey: .selectedSessionID)
        try container.encode(page, forKey: .page)
        try container.encode(pageCount, forKey: .pageCount)
        try container.encode(hasPrevious, forKey: .hasPrevious)
        try container.encode(hasNext, forKey: .hasNext)
        try container.encode(buttons, forKey: .buttons)
    }}
}}

public struct HealthResponse: Codable, Equatable, Sendable {{
    public let status: String
    public let focusEnabled: Bool
    public let launchEnabled: Bool
    public let actionsEnabled: Bool
    public let providers: [String: [String]]
    public let unavailableProviders: [String: String]
    public let accessibilityTrusted: Bool

    public init(
        status: String = "ok",
        focusEnabled: Bool,
        launchEnabled: Bool,
        actionsEnabled: Bool,
        providers: [String: [String]],
        unavailableProviders: [String: String],
        accessibilityTrusted: Bool
    ) {{
        self.status = status
        self.focusEnabled = focusEnabled
        self.launchEnabled = launchEnabled
        self.actionsEnabled = actionsEnabled
        self.providers = providers
        self.unavailableProviders = unavailableProviders
        self.accessibilityTrusted = accessibilityTrusted
    }}

    private enum CodingKeys: String, CodingKey {{
        case status, providers
        case focusEnabled = "focus_enabled"
        case launchEnabled = "launch_enabled"
        case actionsEnabled = "actions_enabled"
        case unavailableProviders = "unavailable_providers"
        case accessibilityTrusted = "accessibility_trusted"
    }}
}}

public struct APIErrorResponse: Codable, Equatable, Sendable {{
    public let error: String
    public let retryable: Bool?

    public init(error: String, retryable: Bool? = nil) {{
        self.error = error
        self.retryable = retryable
    }}
}}

public struct DeckActionRequest: Codable, Equatable, Sendable {{
    public let clientID: String
    public let buttonID: String
    public let revision: Int

    public init(clientID: String, buttonID: String, revision: Int) {{
        self.clientID = clientID
        self.buttonID = buttonID
        self.revision = revision
    }}

    private enum CodingKeys: String, CodingKey {{
        case clientID = "client_id"
        case buttonID = "button_id"
        case revision
    }}
}}

public struct DeckActivationResponse: Codable, Equatable, Sendable {{
    public let accepted: Bool
    public let action: DeckResponseAction
    public let snapshot: DeckSnapshot?
    public let focus: [String: JSONValue]?
    public let launch: [String: JSONValue]?
    public let command: [String: JSONValue]?

    public init(
        accepted: Bool,
        action: DeckResponseAction,
        snapshot: DeckSnapshot? = nil,
        focus: [String: JSONValue]? = nil,
        launch: [String: JSONValue]? = nil,
        command: [String: JSONValue]? = nil
    ) {{
        self.accepted = accepted
        self.action = action
        self.snapshot = snapshot
        self.focus = focus
        self.launch = launch
        self.command = command
    }}

    public init(
        accepted: Bool,
        action: DeckAction,
        snapshot: DeckSnapshot? = nil
    ) {{
        self.init(
            accepted: accepted,
            action: DeckResponseAction(rawValue: action.rawValue)!,
            snapshot: snapshot
        )
    }}
}}
"""


def ts_literal(value: Any, quote: str) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace(quote, f"\\{quote}")
        return f"{quote}{escaped}{quote}"
    return json.dumps(value, separators=(",", ":"))


def ts_type(schema: dict[str, Any], quote: str) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "oneOf" in schema:
        return " | ".join(ts_type(choice, quote) for choice in schema["oneOf"])
    if "const" in schema:
        return ts_literal(schema["const"], quote)
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if isinstance(kind, list):
        return " | ".join("null" if item == "null" else ts_type({"type": item}, quote) for item in kind)
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{ts_type(schema['items'], quote)}>"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional, quote)}>"
        return "Record<string, unknown>"
    raise ValueError(f"unsupported TypeScript schema: {schema}")


def ts_union(name: str, values: list[str], quote: str, semi: str) -> str:
    return f"export type {name} = " + " | ".join(ts_literal(value, quote) for value in values) + semi


def ts_interface(
    name: str,
    schema: dict[str, Any],
    quote: str,
    semi: str,
    replacements: dict[str, str] | None = None,
) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in schema["properties"].items():
        value_type = ts_type(property_schema, quote)
        if replacements:
            value_type = replacements.get(property_name, value_type)
        optional = "" if property_name in required else "?"
        lines.append(f"  {property_name}{optional}: {value_type}{semi}")
    lines.append("}")
    return "\n".join(lines)


def render_typescript(document: dict[str, Any], *, web: bool) -> str:
    all_schemas = schemas(document)
    header = generated_header(document)
    quote = "'" if web else '"'
    semi = "" if web else ";"
    response_focus = all_schemas["DeckActionResponse"]["properties"]["action"]["oneOf"][1]["const"]
    blocks = [
        ts_union("DeckButtonKind", enum_values(all_schemas, "DeckButtonKind"), quote, semi),
        ts_union("DeckIconName", enum_values(all_schemas, "DeckIconName"), quote, semi),
        ts_union("DeckButtonColor", enum_values(all_schemas, "DeckButtonColor"), quote, semi),
        ts_union(
            "DeckButtonConfidence",
            enum_values(all_schemas, "DeckButtonConfidence"),
            quote,
            semi,
        ),
        ts_union("DeckButtonAction", enum_values(all_schemas, "DeckAction"), quote, semi),
        f"export type DeckAction = DeckButtonAction | {ts_literal(response_focus, quote)}{semi}",
        ts_union("CommandID", enum_values(all_schemas, "CommandID"), quote, semi),
        ts_interface(
            "DeckButton",
            all_schemas["DeckButton"],
            quote,
            semi,
            {"action": "DeckButtonAction | null"},
        ),
        ts_interface("DeckSnapshot", all_schemas["DeckSnapshot"], quote, semi),
        ts_interface("DeckActionRequest", all_schemas["DeckActionRequest"], quote, semi),
        ts_interface(
            "DeckActionResponse",
            all_schemas["DeckActionResponse"],
            quote,
            semi,
            {"action": "DeckAction"},
        ),
        ts_interface("HealthResponse", all_schemas["HealthResponse"], quote, semi),
        ts_interface("APIErrorResponse", all_schemas["APIErrorResponse"], quote, semi),
    ]
    if web:
        blocks.extend(
            [
                "export type DeckActivateRequest = DeckActionRequest",
                "export type DeckActivateResponse = DeckActionResponse",
            ]
        )
    else:
        blocks.append("export type DeckActivationResponse = DeckActionResponse;")

    schema_json = json.dumps(all_schemas, indent=2, sort_keys=True)
    schema_json = schema_json.replace('"', quote) if quote == "'" else schema_json
    statement_end = semi
    parse_response_name = "parseDeckActivateResponse" if web else "parseActivationResponse"
    return (
        f"// {header}\n// Do not edit directly.\n\n"
        + "\n\n".join(blocks)
        + f"""

interface Schema {{
  $ref?: string{semi}
  type?: string | string[]{semi}
  enum?: unknown[]{semi}
  const?: unknown{semi}
  oneOf?: Schema[]{semi}
  properties?: Record<string, Schema>{semi}
  required?: string[]{semi}
  additionalProperties?: boolean | Schema{semi}
  items?: Schema{semi}
  minLength?: number{semi}
  maxLength?: number{semi}
  pattern?: string{semi}
  minimum?: number{semi}
  maximum?: number{semi}
  minItems?: number{semi}
  maxItems?: number{semi}
  uniqueItems?: boolean{semi}
  {quote}x-uniqueProperty{quote}?: string{semi}
}}

const SCHEMAS: Record<string, Schema> = {schema_json}{statement_end}

export function parseDeckSnapshot(value: unknown): DeckSnapshot {{
  const buttons = isRecord(value) ? value.buttons : undefined
  const snapshotSchema = contractSchema({quote}DeckSnapshot{quote})
  const buttonSchema = snapshotSchema.properties?.buttons
  const expectedCount = buttonSchema?.minItems
  if (
    !Array.isArray(buttons) ||
    buttonSchema === undefined ||
    expectedCount === undefined ||
    buttonSchema.maxItems !== expectedCount ||
    buttons.length !== expectedCount
  ) {{
    throw new Error(`snapshot must contain exactly ${{expectedCount ?? {quote}the required number of{quote}}} buttons`)
  }}
  const positions = buttons.map((button) => isRecord(button) ? button.position : undefined)
  if (
    new Set(positions).size !== buttons.length ||
    positions.some((position) =>
      typeof position !== {quote}number{quote} ||
      !Number.isSafeInteger(position) ||
      position < 0 ||
      position >= expectedCount
    )
  ) {{
    throw new Error(`snapshot buttons must occupy each position from 0 through ${{expectedCount - 1}} exactly once`)
  }}
  validate(value, snapshotSchema, {quote}snapshot{quote})
  return value as DeckSnapshot
}}

export function {parse_response_name}(value: unknown): DeckActionResponse {{
  validate(value, contractSchema({quote}DeckActionResponse{quote}), {quote}activation response{quote})
  return value as DeckActionResponse
}}

export function parseHealthResponse(value: unknown): HealthResponse {{
  validate(value, contractSchema({quote}HealthResponse{quote}), {quote}health response{quote})
  return value as HealthResponse
}}

export function parseAPIErrorResponse(value: unknown): APIErrorResponse {{
  validate(value, contractSchema({quote}APIErrorResponse{quote}), {quote}error response{quote})
  return value as APIErrorResponse
}}

export function parseDeckActionRequest(value: unknown): DeckActionRequest {{
  validate(value, contractSchema({quote}DeckActionRequest{quote}), {quote}action request{quote})
  return value as DeckActionRequest
}}

function validate(value: unknown, schema: Schema, path: string): void {{
  if (schema.$ref !== undefined) {{
    const name = schema.$ref.split({quote}/{quote}).at(-1)
    const referenced = name === undefined ? undefined : SCHEMAS[name]
    if (referenced === undefined) {{
      throw new Error(`${{path}} references an unknown schema`)
    }}
    validate(value, referenced, path)
    return
  }}
  if (schema.oneOf !== undefined) {{
    const matches = schema.oneOf.filter((choice) => {{
      try {{
        validate(value, choice, path)
        return true
      }} catch {{
        return false
      }}
    }})
    if (matches.length !== 1) throw new Error(`${{path}} does not match exactly one allowed shape`)
    return
  }}
  if (schema.const !== undefined && value !== schema.const) {{
    throw new Error(`${{path}} must equal ${{String(schema.const)}}`)
  }}
  if (schema.enum !== undefined && !schema.enum.includes(value)) {{
    throw new Error(`${{path}} is unsupported`)
  }}

  const allowedTypes = Array.isArray(schema.type) ? schema.type : [schema.type]
  if (allowedTypes.includes({quote}null{quote}) && value === null) return
  const kind = allowedTypes.find((candidate) => candidate !== {quote}null{quote})
  if (kind === undefined) {{
    if (allowedTypes.includes({quote}null{quote})) throw new Error(`${{path}} must be null`)
    return
  }}

  if (kind === {quote}object{quote}) {{
    if (!isRecord(value)) throw new Error(`${{path}} must be an object`)
    const properties = schema.properties ?? {{}}
    for (const required of schema.required ?? []) {{
      if (!Object.prototype.hasOwnProperty.call(value, required)) {{
        throw new Error(`${{path}}.${{required}} is required`)
      }}
    }}
    if (schema.additionalProperties === false) {{
      for (const key of Object.keys(value)) {{
        if (properties[key] === undefined) throw new Error(`${{path}}.${{key}} is not allowed`)
      }}
    }}
    for (const [key, propertySchema] of Object.entries(properties)) {{
      if (Object.prototype.hasOwnProperty.call(value, key)) {{
        validate(value[key], propertySchema, `${{path}}.${{key}}`)
      }}
    }}
    if (typeof schema.additionalProperties === {quote}object{quote}) {{
      for (const [key, item] of Object.entries(value)) {{
        if (properties[key] === undefined) validate(item, schema.additionalProperties, `${{path}}.${{key}}`)
      }}
    }}
    return
  }}
  if (kind === {quote}array{quote}) {{
    if (!Array.isArray(value)) throw new Error(`${{path}} must be an array`)
    if (schema.minItems !== undefined && value.length < schema.minItems) {{
      throw new Error(`${{path}} must contain at least ${{schema.minItems}} items`)
    }}
    if (schema.maxItems !== undefined && value.length > schema.maxItems) {{
      throw new Error(`${{path}} must contain at most ${{schema.maxItems}} items`)
    }}
    value.forEach((item, index) => validate(item, schema.items ?? {{}}, `${{path}}[${{index}}]`))
    if (schema.uniqueItems && new Set(value.map(stableValue)).size !== value.length) {{
      throw new Error(`${{path}} items must be unique`)
    }}
    const uniqueProperty = schema[{quote}x-uniqueProperty{quote}]
    if (uniqueProperty !== undefined) {{
      const values = value.map((item) => isRecord(item) ? item[uniqueProperty] : undefined)
      if (new Set(values.map(stableValue)).size !== value.length) {{
        throw new Error(`${{path}}.${{uniqueProperty}} values must be unique`)
      }}
    }}
    return
  }}
  if (kind === {quote}string{quote}) {{
    if (typeof value !== {quote}string{quote}) throw new Error(`${{path}} must be a string`)
    if (schema.minLength !== undefined && value.length < schema.minLength) {{
      throw new Error(`${{path}} is too short`)
    }}
    if (schema.maxLength !== undefined && value.length > schema.maxLength) {{
      throw new Error(`${{path}} is too long`)
    }}
    if (schema.pattern !== undefined && !new RegExp(schema.pattern).test(value)) {{
      throw new Error(`${{path}} has an invalid format`)
    }}
    return
  }}
  if (kind === {quote}integer{quote}) {{
    if (typeof value !== {quote}number{quote} || !Number.isSafeInteger(value)) {{
      throw new Error(`${{path}} must be an integer`)
    }}
    validateBounds(value, schema, path)
    return
  }}
  if (kind === {quote}number{quote}) {{
    if (typeof value !== {quote}number{quote} || !Number.isFinite(value)) {{
      throw new Error(`${{path}} must be a number`)
    }}
    validateBounds(value, schema, path)
    return
  }}
  if (kind === {quote}boolean{quote} && typeof value !== {quote}boolean{quote}) {{
    throw new Error(`${{path}} must be a boolean`)
  }}
}}

function validateBounds(value: number, schema: Schema, path: string): void {{
  if (schema.minimum !== undefined && value < schema.minimum) {{
    throw new Error(`${{path}} must be at least ${{schema.minimum}}`)
  }}
  if (schema.maximum !== undefined && value > schema.maximum) {{
    throw new Error(`${{path}} must be at most ${{schema.maximum}}`)
  }}
}}

function isRecord(value: unknown): value is Record<string, unknown> {{
  return typeof value === {quote}object{quote} && value !== null && !Array.isArray(value)
}}

function stableValue(value: unknown): string {{
  return JSON.stringify(value)
}}

function contractSchema(name: string): Schema {{
  const schema = SCHEMAS[name]
  if (schema === undefined) throw new Error(`generated schema ${{name}} is unavailable`)
  return schema
}}
"""
    )


def generated(document: dict[str, Any]) -> dict[Path, str]:
    return {
        SWIFT_OUTPUT: render_swift(document),
        WEB_OUTPUT: render_typescript(document, web=True),
        STREAMDECK_OUTPUT: render_typescript(document, web=False),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated files differ instead of writing them",
    )
    args = parser.parse_args()
    expected = generated(load_source())
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text() != content
    ]
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated contract: {path.relative_to(ROOT)}", file=sys.stderr)
            print("run: python3 scripts/generate_http_contracts.py", file=sys.stderr)
            return 1
        print("generated HTTP contracts are current")
        return 0
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
